/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Cadastro;
import Visao.Opcoes.SelecionarOpcoes;

/**
 *
 * @author guto4
 */
public class CadastroDentistaConcluido extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDentistaConcluido
     */
    public CadastroDentistaConcluido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CadastroDentista = new javax.swing.JButton();
        CadastroEndereco = new javax.swing.JButton();
        VoltarMenuOpcoes = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Dentista Concluido");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Cadastro Realizado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 50, 110, 16);

        CadastroDentista.setText("Realizar Outro Cadastro");
        CadastroDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroDentista);
        CadastroDentista.setBounds(150, 90, 230, 23);

        CadastroEndereco.setText("Cadastrar O Endereco Do Dentista");
        CadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroEndereco);
        CadastroEndereco.setBounds(150, 120, 230, 23);

        VoltarMenuOpcoes.setText("Retornar Ao Menu De Opções");
        VoltarMenuOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarMenuOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarMenuOpcoes);
        VoltarMenuOpcoes.setBounds(150, 150, 230, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDentistaActionPerformed
    dispose();
    new CadastroDentista().setVisible(true);
    }//GEN-LAST:event_CadastroDentistaActionPerformed

    private void VoltarMenuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuOpcoesActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_VoltarMenuOpcoesActionPerformed

    private void CadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroEnderecoActionPerformed
    dispose();
    new CadastroDentistaEndereco().setVisible(true);
    }//GEN-LAST:event_CadastroEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDentistaConcluido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroDentista;
    private javax.swing.JButton CadastroEndereco;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton VoltarMenuOpcoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
