/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Cadastro;
import java.awt.*;
import javax.swing.*;
import Modelo.EnderecoM;
import Controle.EnderecoC;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import java.awt.event.KeyEvent;

/**
 *
 * @author guto4
 */
public class CadastroDentistaEndereco extends javax.swing.JFrame {
    int countCPF = 0;
    int countCEP = 0;
    /**
     * Creates new form CadastroDentistaEndereco
     */
    public CadastroDentistaEndereco() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        tCPF = new javax.swing.JTextField();
        tEstado = new javax.swing.JTextField();
        tCidade = new javax.swing.JTextField();
        tCep = new javax.swing.JTextField();
        tBairro = new javax.swing.JTextField();
        tRua = new javax.swing.JTextField();
        tNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ConcluirCadastro = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Endereco");
        setMaximumSize(new java.awt.Dimension(801, 528));
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 80, 30);

        tCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCPFKeyTyped(evt);
            }
        });
        getContentPane().add(tCPF);
        tCPF.setBounds(600, 230, 160, 22);
        getContentPane().add(tEstado);
        tEstado.setBounds(600, 260, 160, 22);
        getContentPane().add(tCidade);
        tCidade.setBounds(600, 290, 160, 22);

        tCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCepKeyTyped(evt);
            }
        });
        getContentPane().add(tCep);
        tCep.setBounds(600, 320, 160, 22);
        getContentPane().add(tBairro);
        tBairro.setBounds(600, 350, 160, 22);
        getContentPane().add(tRua);
        tRua.setBounds(600, 380, 160, 22);
        getContentPane().add(tNumero);
        tNumero.setBounds(600, 410, 160, 22);

        jLabel1.setText("CPF Do Dentista");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(497, 230, 100, 20);

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 260, 100, 20);

        jLabel3.setText("Cidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 290, 100, 20);

        jLabel4.setText("Cep");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 320, 100, 20);

        jLabel5.setText("Bairro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 350, 100, 20);

        jLabel6.setText("Rua");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 380, 100, 20);

        jLabel7.setText("Numero");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 410, 100, 20);

        ConcluirCadastro.setText("Concluir Cadastro");
        ConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(ConcluirCadastro);
        ConcluirCadastro.setBounds(600, 450, 160, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirCadastroActionPerformed
    String CPF = tCPF.getText();
    String Estado = tEstado.getText();
    String Cidade = tCidade.getText();
    String Cep = tCep.getText();
    String Bairro = tBairro.getText();
    String Rua = tRua.getText();
    int Numero = Integer.parseInt(tNumero.getText());

    EnderecoM end = new EnderecoM(CPF,Estado,Cidade,Cep,Bairro,Rua,Numero);
    EnderecoC endc = new EnderecoC();
    endc.CadastroEnderecoDentistas(end);

    dispose();
    new CadastroEnderecoConcluido().setVisible(true);
    }//GEN-LAST:event_ConcluirCadastroActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void tCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCPFKeyTyped
       if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        tCPF.setText(tCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       tCPF.setText(tCPF.getText() + ".");
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        tCPF.setText(tCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if(countCPF == 1){
        countCPF = countCPF-2;
        }
        else if(countCPF == 2){
        countCPF = countCPF-2;
        }
        else if(countCPF == 3){
        countCPF = countCPF-2;
        }

    }
    }//GEN-LAST:event_tCPFKeyTyped

    private void tCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCepKeyTyped
            if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCep.getText().isEmpty()){
          countCEP = 0;
        }
    countCEP = countCEP+1;
        if (countCEP == 3)
    {
        tCep.setText(tCep.getText() + ".");
        countCEP = countCEP+1;
    }
    if (countCEP == 7)
    {
       tCep.setText(tCep.getText() + "-");
       countCEP = countCEP+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCEP > 0){
            countCEP = countCEP-1;
        }
        else if(countCEP == 1){
        countCEP = countCEP-2;
        }
        else if(countCPF == 3){
        countCEP = countCEP-2;
        }

    }
    }//GEN-LAST:event_tCepKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDentistaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDentistaEndereco().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontologia Temporaria.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        tCPF.setBounds(
                cx - 28,
                cy - 122,
                160,
                22
        );

        tEstado.setBounds(
                cx - 28,
                cy - 92,
                160,
                22
        );

        tCidade.setBounds(
                cx - 28,
                cy - 62,
                160,
                22
        );

        tCep.setBounds(
                cx - 28,
                cy - 32,
                160,
                22
        );

        tBairro.setBounds(
                cx - 28,
                cy - 2,
                160,
                22
        );

        tRua.setBounds(
                cx - 28,
                cy + 28,
                160,
                22
        );

        tNumero.setBounds(
                cx - 28,
                cy + 58,
                160,
                22
        );

        jLabel1.setBounds(
                cx - 132,
                cy - 122,
                100,
                20
        );

        jLabel2.setBounds(
                cx - 128,
                cy - 92,
                100,
                20
        );

        jLabel3.setBounds(
                cx - 128,
                cy - 62,
                100,
                20
        );

        jLabel4.setBounds(
                cx - 128,
                cy - 32,
                100,
                20
        );

        jLabel5.setBounds(
                cx - 128,
                cy - 2,
                100,
                20
        );

        jLabel6.setBounds(
                cx - 128,
                cy + 28,
                100,
                20
        );

        jLabel7.setBounds(
                cx - 128,
                cy + 58,
                100,
                20
        );

        ConcluirCadastro.setBounds(
                cx - 28,
                cy + 98,
                160,
                23
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                80,
                30
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConcluirCadastro;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tBairro;
    private javax.swing.JTextField tCPF;
    private javax.swing.JTextField tCep;
    private javax.swing.JTextField tCidade;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTextField tRua;
    // End of variables declaration//GEN-END:variables
}
