/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Cadastro;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import Modelo.DadosPessoaisM;
import Controle.DadosPessoaisC;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import Conexao.Conexao;

public class CadastroDentista extends javax.swing.JFrame {
    int countCPF = 0;
    int countContato = 0;
    int countData = 0;
    ResultSet resposta=null;
    
    /**
     * Creates new form CadastroDentista
     */
    public CadastroDentista() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        tNome = new javax.swing.JTextField();
        tCPF = new javax.swing.JTextField();
        tDataNasc = new javax.swing.JTextField();
        tContato = new javax.swing.JTextField();
        tSexo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConcluirCadastro = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Dentistas");
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 70, 30);
        getContentPane().add(tNome);
        tNome.setBounds(591, 250, 190, 24);

        tCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCPFActionPerformed(evt);
            }
        });
        tCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCPFKeyTyped(evt);
            }
        });
        getContentPane().add(tCPF);
        tCPF.setBounds(590, 280, 190, 24);

        tDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDataNascKeyTyped(evt);
            }
        });
        getContentPane().add(tDataNasc);
        tDataNasc.setBounds(590, 310, 190, 24);

        tContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tContatoKeyTyped(evt);
            }
        });
        getContentPane().add(tContato);
        tContato.setBounds(590, 340, 190, 24);
        getContentPane().add(tSexo);
        tSexo.setBounds(590, 370, 190, 24);

        jLabel1.setText("Nome Do Dentista");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 250, 130, 20);

        jLabel2.setText("CPF Do Dentista");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 280, 130, 20);

        jLabel3.setText("Data De Nascimento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 310, 130, 20);

        jLabel4.setText("Contato");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 340, 130, 20);

        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 370, 130, 20);

        ConcluirCadastro.setText("Concluir Cadastro");
        ConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(ConcluirCadastro);
        ConcluirCadastro.setBounds(590, 420, 190, 24);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirCadastroActionPerformed

        String CPF = tCPF.getText();
        String Nome = tNome.getText();
        String DataNasc = tDataNasc.getText();
        String Contato = tContato.getText();
        String Sexo1 = tSexo.getText();
        char Sexo = Sexo1.charAt(0);
        DadosPessoaisC dc = new DadosPessoaisC();
        DadosPessoaisM dm = new DadosPessoaisM(Nome,CPF,DataNasc,Contato,Sexo);
        dc.CadastroGeralDentistas(dm);
    new CadastroDentistaConcluido().setVisible(true);
    dispose();
        
        


    }//GEN-LAST:event_ConcluirCadastroActionPerformed

    private void tCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCPFKeyTyped
       if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        tCPF.setText(tCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       tCPF.setText(tCPF.getText() + "."); 
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        tCPF.setText(tCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if (countCPF == 1)
        {
        countCPF = countCPF-2;
        }
        else if (countCPF == 2)
        {
       countCPF = countCPF-2;
        }
        else if (countCPF == 3)
        {
        countCPF = countCPF-2;
        }
        
    }
    }//GEN-LAST:event_tCPFKeyTyped

    private void tDataNascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDataNascKeyTyped

    
    if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tDataNasc.getText().isEmpty()){
            countData = 0;
        }
            countData = countData+1;
        if (countData == 3)
    {
        tDataNasc.setText(tDataNasc.getText() + "/");
        countData = countData+1;
    }
    if (countData == 6)
    {
       tDataNasc.setText(tDataNasc.getText() + "/");
       countData = countData+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countData > 0){
            countData = countData-1;
        }
        else if(countData == 1){
        countData = countData-2;    
        }
        else if(countData == 3){
        countData = countData-2;    
        }
        
    }
    }//GEN-LAST:event_tDataNascKeyTyped

    private void tContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tContatoKeyTyped

    
    if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tContato.getText().isEmpty()){
            countContato = 0;
        }
    countContato = countContato+1;
        if (countContato == 1)
    {
        tContato.setText(tContato.getText() + "(");
        countContato = countContato+1;
    }
    if (countContato == 4)
    {
       tContato.setText(tContato.getText() + ")"); 
       countContato = countContato+1;
    }
    if (countContato == 10){
        tContato.setText(tContato.getText() + "-");
        countContato = countContato+1;
    }
    }
  
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countContato > 0){
            countContato = countContato-1;
        }
        else if(countContato == 1){
        countContato = countContato-2;    
        }
        else if(countContato == 4){
        countContato = countContato-2;    
        }
        else if(countContato == 9){
        countContato = countContato-2;    
        }
        
    }
    }//GEN-LAST:event_tContatoKeyTyped

    private void tCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDentista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConcluirCadastro;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tCPF;
    private javax.swing.JTextField tContato;
    private javax.swing.JTextField tDataNasc;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tSexo;
    // End of variables declaration//GEN-END:variables
}
