/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Consulta;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.Pacientes.OpcoesPacientes;
import Visao.Opcoes.Pacientes.Agendamento.ConsultaAgendamentos;

/**
 *
 * @author guto4
 */
public class ConsultaPacientes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPacientes
     */
    public ConsultaPacientes() {
        initComponents();

        getContentPane().setComponentZOrder(
                jLabel1,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        ConsultaPacientes = new javax.swing.JButton();
        ConsultaDeEndereco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Pacientes");
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 54, 30);

        ConsultaPacientes.setText("Consultar Pacientes Cadastrados");
        ConsultaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaPacientes);
        ConsultaPacientes.setBounds(280, 230, 220, 23);

        ConsultaDeEndereco.setText("Consultar Enderecos De Pacientes");
        ConsultaDeEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaDeEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaDeEndereco);
        ConsultaDeEndereco.setBounds(280, 270, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaDeEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDeEnderecoActionPerformed
    dispose();
    new ConsultaPacientesEndereco().setVisible(true);
    }//GEN-LAST:event_ConsultaDeEnderecoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesPacientes().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConsultaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPacientesActionPerformed
    dispose();
    new ConsultaPacientesCadastrados().setVisible(true);
    }//GEN-LAST:event_ConsultaPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPacientes().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontologia Temporaria.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                jLabel1.getWidth(),
                jLabel1.getHeight(),
                Image.SCALE_SMOOTH
        );

        jLabel1.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        jLabel1.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        ConsultaPacientes.setBounds(
                cx - 110,
                cy - 32,
                220,
                23
        );

        ConsultaDeEndereco.setBounds(
                cx - 110,
                cy + 8,
                220,
                23
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                54,
                30
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaDeEndereco;
    private javax.swing.JButton ConsultaPacientes;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
