/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Consulta;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import Controle.DadosPessoaisC;
import java.awt.event.KeyEvent;

/**
 *
 * @author guto4
 */
public class ConsultaPacientesCadastrados extends javax.swing.JFrame {
    DefaultTableModel campotabela = new DefaultTableModel();
    ResultSet resposta=null;
    DadosPessoaisC dpc = new DadosPessoaisC();
    int countCPF = 0;

    public ConsultaPacientesCadastrados() {
        initComponents();
        campotabela.addColumn ("NOME:");
        campotabela.addColumn ("CPF:");
        campotabela.addColumn ("DATA_NASC:");
        campotabela.addColumn ("CONTATO:");
        campotabela.addColumn ("SEXO:");
        jTableDP.setModel(campotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDP = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BuscaPorCPF = new javax.swing.JButton();
        ConsultaGeral = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jCPF = new javax.swing.JTextField();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        jTableDP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDP);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 130, 800, 320);

        jLabel2.setText("Insira o Cpf do paciente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 30, 140, 20);

        BuscaPorCPF.setText("Consulta por CPF");
        BuscaPorCPF.setActionCommand("");
        BuscaPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaPorCPFActionPerformed(evt);
            }
        });
        getContentPane().add(BuscaPorCPF);
        BuscaPorCPF.setBounds(660, 70, 130, 23);

        ConsultaGeral.setText("Consulta Geral");
        ConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaGeralActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaGeral);
        ConsultaGeral.setBounds(520, 70, 130, 23);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 470, 80, 30);

        jCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPFKeyTyped(evt);
            }
        });
        getContentPane().add(jCPF);
        jCPF.setBounds(660, 30, 130, 22);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaGeralActionPerformed
        try {
            resposta = dpc.ConsultaGeralClientes();
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i<=4){
                        jTableDP.setValueAt(resposta.getString(i),linha,i-1);
                    }
                    else 
                        jTableDP.setValueAt(resposta.getArray(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();
            
        }
    }//GEN-LAST:event_ConsultaGeralActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new ConsultaPacientes().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void BuscaPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaPorCPFActionPerformed
        try {
            String CPF = jCPF.getText();
        resposta = dpc.ConsultaPorCPFClientes(CPF);
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i<=4){
                        jTableDP.setValueAt(resposta.getString(i),linha,i-1);
                    }
                    else 
                        jTableDP.setValueAt(resposta.getArray(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();
            
        }
    }//GEN-LAST:event_BuscaPorCPFActionPerformed

    private void jCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPFKeyTyped
         if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(jCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        jCPF.setText(jCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       jCPF.setText(jCPF.getText() + "."); 
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        jCPF.setText(jCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if(countCPF == 1){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 2){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 3){
        countCPF = countCPF-2;    
        }
        
    }
    }//GEN-LAST:event_jCPFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPacientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPacientesCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaPorCPF;
    private javax.swing.JButton ConsultaGeral;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField jCPF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDP;
    // End of variables declaration//GEN-END:variables
}
