/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Agendamento;
import Visao.Opcoes.Pacientes.OpcoesPacientes;
import Visao.Opcoes.Pacientes.Agendamento.NovoAgendamento;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author guto4
 */
public class Agendamento extends javax.swing.JFrame {

    /**
     * Creates new form Agendamento
     */
    public Agendamento() {
        initComponents();
        ConfigurarImagem();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        addComponentListener(new java.awt.event.ComponentAdapter(){
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });
        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        NovoAgendamento = new javax.swing.JButton();
        DeletarAgendamento = new javax.swing.JButton();
        ConsultaAgendamento = new javax.swing.JButton();
        AtualizarAgendamento = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamentos");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 70, 30);

        NovoAgendamento.setText("Realizar Um Novo Agendamento");
        NovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(NovoAgendamento);
        NovoAgendamento.setBounds(270, 230, 250, 23);

        DeletarAgendamento.setText("Deletar Um Agendamento Já Existente");
        DeletarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(DeletarAgendamento);
        DeletarAgendamento.setBounds(270, 320, 250, 23);

        ConsultaAgendamento.setText("Consultar Agendamentos");
        ConsultaAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaAgendamento);
        ConsultaAgendamento.setBounds(270, 260, 250, 23);

        AtualizarAgendamento.setText("Atualizar Agendamento");
        AtualizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizarAgendamento);
        AtualizarAgendamento.setBounds(270, 290, 250, 23);

        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigurarImagem() {

        java.net.URL url = getClass()
                .getResource("/Imagem/Odontologia Temporaria.png");

        if (url == null) {
            System.out.println("Imagem não encontrada!");
            return;
        }


        Image imagem = new ImageIcon(url).getImage();


        Imagem = new JLabel() {

            @Override
            protected void paintComponent(java.awt.Graphics g) {

                super.paintComponent(g);

                g.drawImage(
                        imagem,
                        0,
                        0,
                        getWidth(),
                        getHeight(),
                        this
                );
            }
        };


        getContentPane().add(Imagem);
        getContentPane().setComponentZOrder(AtualizarAgendamento, 0);
        getContentPane().setComponentZOrder(ConsultaAgendamento, 0);
        getContentPane().setComponentZOrder(DeletarAgendamento, 0);
        getContentPane().setComponentZOrder(NovoAgendamento, 0);
        getContentPane().setComponentZOrder(Voltar, 0);

    }

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesPacientes().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void NovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoAgendamentoActionPerformed
    dispose();
    new NovoAgendamento().setVisible(true);
    }//GEN-LAST:event_NovoAgendamentoActionPerformed

    private void DeletarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarAgendamentoActionPerformed
    dispose();
    new DeletarAgendamento().setVisible(true);
    }//GEN-LAST:event_DeletarAgendamentoActionPerformed

    private void ConsultaAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAgendamentoActionPerformed
    dispose();
    new ConsultaAgendamentos().setVisible(true);
    }//GEN-LAST:event_ConsultaAgendamentoActionPerformed

    private void AtualizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarAgendamentoActionPerformed
    dispose();
    new AtualizarAgendamento().setVisible(true);
    }//GEN-LAST:event_AtualizarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();


        // imagem ocupa toda a tela
        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );


        int larguraBotao = 220;
        int alturaBotao = 30;


        int x = (largura - larguraBotao) / 2;

        int y = (altura / 2) - 50;

        AtualizarAgendamento.setBounds(
                x,
                y+80,
                larguraBotao,
                alturaBotao
        );

        ConsultaAgendamento.setBounds(
                x,
                y+40,
                larguraBotao,
                alturaBotao
        );

        DeletarAgendamento.setBounds(
                x,
                y+120,
                larguraBotao,
                alturaBotao
        );

        NovoAgendamento.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );


        Voltar.setBounds(
                15,
                altura - 60,
                45,
                45
        );



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarAgendamento;
    private javax.swing.JButton ConsultaAgendamento;
    private javax.swing.JButton DeletarAgendamento;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton NovoAgendamento;
    private javax.swing.JButton Voltar;
    // End of variables declaration//GEN-END:variables
}
