/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Agendamento;
import Visao.Opcoes.SelecionarOpcoes;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author guto4
 */
public class AgendamentoDeletado extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form AgendamentoDeletado
     */
    public AgendamentoDeletado() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExcluirNovamente = new javax.swing.JButton();
        AgendarNovamente = new javax.swing.JButton();
        ConsultarAgendamentos = new javax.swing.JButton();
        Retornar = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento Deletado");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        jLabel1.setText("Exclusão Concluida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 110, 16);

        ExcluirNovamente.setText("Realizar Outra Exclusão De Agendamento");
        ExcluirNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(ExcluirNovamente);
        ExcluirNovamente.setBounds(110, 70, 260, 23);

        AgendarNovamente.setText("Adicionar Outro Agendamento");
        AgendarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(AgendarNovamente);
        AgendarNovamente.setBounds(110, 110, 260, 23);

        ConsultarAgendamentos.setText("Consultar Agendamentos Existentes");
        ConsultarAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarAgendamentosActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarAgendamentos);
        ConsultarAgendamentos.setBounds(110, 150, 260, 23);

        Retornar.setText("Retornar Ao Menu De Opcões");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });
        getContentPane().add(Retornar);
        Retornar.setBounds(110, 190, 260, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontoloigia Temporaria2.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ExcluirNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirNovamenteActionPerformed
    dispose();
    new DeletarAgendamento().setVisible(true);
    }//GEN-LAST:event_ExcluirNovamenteActionPerformed

    private void AgendarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarNovamenteActionPerformed
    dispose();
    new NovoAgendamento().setVisible(true);
    }//GEN-LAST:event_AgendarNovamenteActionPerformed

    private void ConsultarAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarAgendamentosActionPerformed
    dispose();
    new ConsultaAgendamentos().setVisible(true);
    }//GEN-LAST:event_ConsultarAgendamentosActionPerformed

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoDeletado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoDeletado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoDeletado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoDeletado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoDeletado().setVisible(true);
            }
        });
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // BOTÕES CENTRAIS
        // =====================================

        int larguraBotao = 260;
        int alturaBotao = 23;
        int espacamento = 10;

        int x = (largura - larguraBotao) / 2;
        int y = (altura / 2) - 80;

        jLabel1.setBounds(
                x + 65,
                y - (alturaBotao + espacamento),
                larguraBotao,
                alturaBotao
        );

        ExcluirNovamente.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );

        AgendarNovamente.setBounds(
                x,
                y + (alturaBotao + espacamento),
                larguraBotao,
                alturaBotao
        );

        ConsultarAgendamentos.setBounds(
                x,
                y + (alturaBotao + espacamento) * 2,
                larguraBotao,
                alturaBotao
        );

        Retornar.setBounds(
                x,
                y + (alturaBotao + espacamento) * 3,
                larguraBotao,
                alturaBotao
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarNovamente;
    private javax.swing.JButton ConsultarAgendamentos;
    private javax.swing.JButton ExcluirNovamente;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Retornar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
