/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Agendamento;
import Visao.Opcoes.SelecionarOpcoes;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author guto4
 */
public class AgendamentoConcluido extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form AgendamentoConcluido
     */
    public AgendamentoConcluido() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        RealizarAgendamento = new javax.swing.JButton();
        ConsultaAgendamento = new javax.swing.JButton();
        Retorna = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        Imagem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Imagem/Odontologia Temporaria.png")
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento Concluido");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);
        jLabel2.setText("Agendamento Realizado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 40, 129, 16);

        RealizarAgendamento.setText("Realizar Um Novo Agendamento");
        RealizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarAgendamento);
        RealizarAgendamento.setBounds(150, 90, 240, 23);

        ConsultaAgendamento.setText("Consultar Agendamentos Existentes");
        ConsultaAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaAgendamento);
        ConsultaAgendamento.setBounds(150, 130, 240, 23);

        Retorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Retorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornaActionPerformed(evt);
            }
        });
        getContentPane().add(Retorna);
        Retorna.setBounds(150, 170, 240, 23);


        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontologia Temporaria.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void RetornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornaActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornaActionPerformed

    private void RealizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarAgendamentoActionPerformed
    dispose();
    new NovoAgendamento().setVisible(true);
    }//GEN-LAST:event_RealizarAgendamentoActionPerformed

    private void ConsultaAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAgendamentoActionPerformed
    dispose();
    new ConsultaAgendamentos().setVisible(true);
    }//GEN-LAST:event_ConsultaAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoConcluido().setVisible(true);
            }
        });
    }
    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // BOTÕES CENTRAIS
        // =====================================

        int larguraBotao = 240;
        int alturaBotao = 30;
        int espacamento = 10;

        int x = (largura - larguraBotao) / 2;
        int y = (altura / 2) - 60;

        jLabel2.setBounds(
                x,
                y - (alturaBotao + espacamento),
                larguraBotao,
                alturaBotao
        );

        RealizarAgendamento.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );

        ConsultaAgendamento.setBounds(
                x,
                y + (alturaBotao + espacamento),
                larguraBotao,
                alturaBotao
        );

        Retorna.setBounds(
                x,
                y + (alturaBotao + espacamento) * 2,
                larguraBotao,
                alturaBotao
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaAgendamento;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton RealizarAgendamento;
    private javax.swing.JButton Retorna;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
