/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Agendamento;
import Visao.Opcoes.SelecionarOpcoes;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author guto4
 */
public class AtualizacaoConcluida extends javax.swing.JFrame {

    /**
     * Creates new form AtualizacaoConcluida
     */
    public AtualizacaoConcluida() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NovaAtualizacao = new javax.swing.JButton();
        NovoAgendamento = new javax.swing.JButton();
        ConsultarAgendamentos = new javax.swing.JButton();
        RetornarAoMenu = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizacão De Agendamento Concluida");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        jLabel1.setText("Atualização De Agendamento Concluida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 230, 30);

        NovaAtualizacao.setText("Realizar Uma Nova Atualização");
        NovaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(NovaAtualizacao);
        NovaAtualizacao.setBounds(140, 70, 230, 23);

        NovoAgendamento.setText("Realizar Um Novo Agendamento");
        NovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(NovoAgendamento);
        NovoAgendamento.setBounds(140, 100, 230, 23);

        ConsultarAgendamentos.setText("Consultar Agendamentos");
        ConsultarAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarAgendamentosActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarAgendamentos);
        ConsultarAgendamentos.setBounds(140, 130, 230, 23);

        RetornarAoMenu.setText("Retornar Ao Menu De Opções");
        RetornarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RetornarAoMenu);
        RetornarAoMenu.setBounds(140, 160, 230, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontoloigia Temporaria2.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void NovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoAgendamentoActionPerformed
    dispose();
    new NovoAgendamento().setVisible(true);
    }//GEN-LAST:event_NovoAgendamentoActionPerformed

    private void NovaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaAtualizacaoActionPerformed
    dispose();
    new AtualizarAgendamento().setVisible(true);
    }//GEN-LAST:event_NovaAtualizacaoActionPerformed

    private void ConsultarAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarAgendamentosActionPerformed
    dispose();
    new ConsultaAgendamentos().setVisible(true);
    }//GEN-LAST:event_ConsultarAgendamentosActionPerformed

    private void RetornarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarAoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoConcluida().setVisible(true);
            }
        });
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // BOTÕES CENTRAIS
        // =====================================

        int larguraBotao = 230;
        int alturaBotao = 23;
        int espacamento = 10;

        int x = (largura - larguraBotao) / 2;
        int y = (altura / 2) - 60;

        jLabel1.setBounds(
                x - 10,
                y - (alturaBotao + espacamento) - 10,
                larguraBotao + 20,
                30
        );

        NovaAtualizacao.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );

        NovoAgendamento.setBounds(
                x,
                y + (alturaBotao + espacamento),
                larguraBotao,
                alturaBotao
        );

        ConsultarAgendamentos.setBounds(
                x,
                y + (alturaBotao + espacamento) * 2,
                larguraBotao,
                alturaBotao
        );

        RetornarAoMenu.setBounds(
                x,
                y + (alturaBotao + espacamento) * 3,
                larguraBotao,
                alturaBotao
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarAgendamentos;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton NovaAtualizacao;
    private javax.swing.JButton NovoAgendamento;
    private javax.swing.JButton RetornarAoMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
