/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Agendamento;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import Controle.AgendamentoC;
import Visao.Opcoes.Pacientes.Consulta.ConsultaPacientes;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author guto4
 */
public class ConsultaAgendamentos extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;
    DefaultTableModel campotabela = new DefaultTableModel();
    ResultSet resposta=null;
    int countCPF  = 0;
    AgendamentoC ag = new AgendamentoC();
    public ConsultaAgendamentos() {
        initComponents();

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setOpaque(false);

        campotabela.addColumn("ID DO AGENDAMENTO:");
        campotabela.addColumn("NOME DO PACIENTE:");
        campotabela.addColumn("NOME DO DENTISTA:");
        campotabela.addColumn("DATA DO AGENDAMENTO:");
        campotabela.addColumn("HORÁRIO");

        jTable1.setModel(campotabela);
        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(
                new java.awt.event.ComponentAdapter() {

                    @Override
                    public void componentResized(
                            java.awt.event.ComponentEvent e) {

                        ajustarTela();
                    }
                }
        );


        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ConsultaGeral = new javax.swing.JButton();
        jCPF = new javax.swing.JTextField();
        BuscaCPF = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        Imagem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Imagem/Odontologia Temporaria.png")
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Agendamentos");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 800, 330);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 463, 70, 30);

        jLabel2.setText("Insira o CPF do Paciente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 30, 160, 20);

        ConsultaGeral.setText("Consulta Geral");
        ConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaGeralActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaGeral);
        ConsultaGeral.setBounds(520, 70, 120, 23);

        jCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPFKeyTyped(evt);
            }
        });
        getContentPane().add(jCPF);
        jCPF.setBounds(670, 30, 110, 22);

        BuscaCPF.setText("Consulta Por CPF");
        BuscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCPFActionPerformed(evt);
            }
        });
        getContentPane().add(BuscaCPF);
        BuscaCPF.setBounds(655, 70, 130, 23);


        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaGeralActionPerformed
        try {
            resposta = ag.ConsultaGeralAgendamento();
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i==1){
                        jTable1.setValueAt(resposta.getInt(i),linha,i-1);
                    }
                    else 
                        jTable1.setValueAt(resposta.getString(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();
            
        }
    }//GEN-LAST:event_ConsultaGeralActionPerformed

    private void BuscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCPFActionPerformed
        try {
            String CPF = jCPF.getText();
            resposta = ag.ConsultaPorCPFAgendamentoClientes(CPF);
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i==1){
                        jTable1.setValueAt(resposta.getInt(i),linha,i-1);
                    }
                    else 
                        jTable1.setValueAt(resposta.getString(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaCPFActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new Agendamento().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void jCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPFKeyTyped
                     if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(jCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        jCPF.setText(jCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       jCPF.setText(jCPF.getText() + "."); 
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        jCPF.setText(jCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if(countCPF == 1){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 2){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 3){
        countCPF = countCPF-2;    
        }
        
    }
    }//GEN-LAST:event_jCPFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAgendamentos().setVisible(true);
            }
        });
    }

    private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontologia Temporaria.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // PESQUISA POR CPF
        // =====================================

        int larguraLabel = 170;
        int larguraCampo = 180;
        int alturaCampo = 25;

        int larguraBotao = 140;
        int alturaBotao = 30;

        int espacamento = 10;


        // Largura total da área superior
        int larguraTotal =
                larguraLabel
                        + espacamento
                        + larguraCampo
                        + espacamento
                        + larguraBotao
                        + espacamento
                        + larguraBotao;


        // Centraliza horizontalmente
        int x = (largura - larguraTotal) / 2;

        int y = 35;


        // =====================================
        // LABEL
        // =====================================

        jLabel2.setBounds(
                x,
                y,
                larguraLabel,
                alturaCampo
        );


        // =====================================
        // CPF
        // =====================================

        int xCPF =
                x + larguraLabel + espacamento;

        jCPF.setBounds(
                xCPF,
                y,
                larguraCampo,
                alturaCampo
        );


        // =====================================
        // CONSULTA GERAL
        // =====================================

        int xConsultaGeral =
                xCPF + larguraCampo + espacamento;

        ConsultaGeral.setBounds(
                xConsultaGeral,
                y,
                larguraBotao,
                alturaBotao
        );


        // =====================================
        // CONSULTA POR CPF
        // =====================================

        int xBuscaCPF =
                xConsultaGeral + larguraBotao + espacamento;

        BuscaCPF.setBounds(
                xBuscaCPF,
                y,
                larguraBotao,
                alturaBotao
        );


        // =====================================
        // TABELA
        // =====================================

        int margem = 40;

        jScrollPane1.setBounds(
                margem,
                100,
                largura - (margem * 2),
                altura - 170
        );


        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                45,
                45
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaCPF;
    private javax.swing.JButton ConsultaGeral;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField jCPF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
