/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Atualizacao;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Dentistas.Consulta.ConsultaDentistaCadastrado;
import Visao.Opcoes.Dentistas.Cadastro.CadastroDentista;

/**
 *
 * @author guto4
 */
public class AtualizacaoDadosConcluida extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form AtualizacaoDadosConcluida
     */
    public AtualizacaoDadosConcluida() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NovaAtualizacao = new javax.swing.JButton();
        CadastrarDentista = new javax.swing.JButton();
        ConsultarDentistas = new javax.swing.JButton();
        RetornarAoMenu = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização De Dados Concluidas");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Atualização De Dados Concluida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 40, 200, 20);

        NovaAtualizacao.setText("Realizar Outra Atualização");
        NovaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(NovaAtualizacao);
        NovaAtualizacao.setBounds(150, 80, 220, 23);

        CadastrarDentista.setText("Cadastrar Um Novo Dentista");
        CadastrarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarDentista);
        CadastrarDentista.setBounds(150, 110, 220, 23);

        ConsultarDentistas.setText("Consultar Dentistas Já Cadastrados");
        ConsultarDentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarDentistasActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarDentistas);
        ConsultarDentistas.setBounds(150, 140, 220, 23);

        RetornarAoMenu.setText("Retornar Ao Menu De Opções");
        RetornarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RetornarAoMenu);
        RetornarAoMenu.setBounds(150, 170, 220, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarAoMenuActionPerformed

    private void ConsultarDentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarDentistasActionPerformed
    dispose();
    new ConsultaDentistaCadastrado().setVisible(true);
    }//GEN-LAST:event_ConsultarDentistasActionPerformed

    private void CadastrarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarDentistaActionPerformed
    dispose();
    new CadastroDentista().setVisible(true);
    }//GEN-LAST:event_CadastrarDentistaActionPerformed

    private void NovaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaAtualizacaoActionPerformed
    dispose();
    new AtualizarDadosDentista().setVisible(true);
    }//GEN-LAST:event_NovaAtualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoDadosConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoDadosConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoDadosConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoDadosConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoDadosConcluida().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontoloigia Temporaria2.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel1.setBounds(
                cx - 90,
                cy - 76,
                200,
                20
        );

        NovaAtualizacao.setBounds(
                cx - 110,
                cy - 36,
                220,
                23
        );

        CadastrarDentista.setBounds(
                cx - 110,
                cy - 6,
                220,
                23
        );

        ConsultarDentistas.setBounds(
                cx - 110,
                cy + 24,
                220,
                23
        );

        RetornarAoMenu.setBounds(
                cx - 110,
                cy + 54,
                220,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarDentista;
    private javax.swing.JButton ConsultarDentistas;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton NovaAtualizacao;
    private javax.swing.JButton RetornarAoMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
