/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Atualizacao;
import Visao.Opcoes.Dentistas.Cadastro.CadastroDentistaEndereco;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Dentistas.Consulta.ConsultaDentistaEndereco;
/**
 *
 * @author guto4
 */
public class AtualizacaoEnderecoConcluida extends javax.swing.JFrame {

    /**
     * Creates new form AtualizacaoEnderecoConcluida
     */
    public AtualizacaoEnderecoConcluida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AdicioarNovoEndereco = new javax.swing.JButton();
        AdicionarEndereco = new javax.swing.JButton();
        ConsultarEnderecos = new javax.swing.JButton();
        RetornarAoMenu = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização De Endereço Concluida");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Atualização De  Endereço Concluida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 190, 16);

        AdicioarNovoEndereco.setText("Realizar Outra Atualização");
        AdicioarNovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicioarNovoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(AdicioarNovoEndereco);
        AdicioarNovoEndereco.setBounds(110, 90, 310, 23);

        AdicionarEndereco.setText("Adicionar Um Novo Endereço De Dentista");
        AdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarEndereco);
        AdicionarEndereco.setBounds(110, 120, 310, 23);

        ConsultarEnderecos.setText("Consultar Os Endereços De Dentistas Já Cadastrados");
        ConsultarEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarEnderecosActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarEnderecos);
        ConsultarEnderecos.setBounds(110, 150, 310, 23);

        RetornarAoMenu.setText("Retornar Ao Menu De Opções");
        RetornarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RetornarAoMenu);
        RetornarAoMenu.setBounds(110, 180, 310, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicioarNovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicioarNovoEnderecoActionPerformed
    dispose();
    new AtualizacaoEnderecoDentista().setVisible(true);
    }//GEN-LAST:event_AdicioarNovoEnderecoActionPerformed

    private void RetornarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarAoMenuActionPerformed

    private void AdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarEnderecoActionPerformed
    dispose();
    new CadastroDentistaEndereco().setVisible(true);
    }//GEN-LAST:event_AdicionarEnderecoActionPerformed

    private void ConsultarEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarEnderecosActionPerformed
    dispose();
    new ConsultaDentistaEndereco().setVisible(true);
    }//GEN-LAST:event_ConsultarEnderecosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoConcluida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoEnderecoConcluida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicioarNovoEndereco;
    private javax.swing.JButton AdicionarEndereco;
    private javax.swing.JButton ConsultarEnderecos;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton RetornarAoMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
