
package Visao.Opcoes.Dentistas.Atualizacao;
import java.awt.*;
import javax.swing.*;
import Controle.EnderecoC;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import java.awt.event.KeyEvent;

/**
 *
 * @author guto4
 */
public class AtualizacaoEnderecoDentista extends javax.swing.JFrame {
    int countCPF = 0;
    int countItem = 0;
    /**
     * Creates new form AtualizacaoEnderecoDentista
     */
    public AtualizacaoEnderecoDentista() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConfirmaAtualizacao = new javax.swing.JButton();
        tCPF = new javax.swing.JTextField();
        tItem = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        tOpcao = new javax.swing.JComboBox<>();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização Endereço Dentista");
        setMaximumSize(new java.awt.Dimension(801, 533));
        setMinimumSize(new java.awt.Dimension(801, 533));
        getContentPane().setLayout(null);

        jLabel1.setText("Informe O CPF Do Dentista");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 360, 150, 20);

        ConfirmaAtualizacao.setText("Confirmar Atualização");
        ConfirmaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmaAtualizacao);
        ConfirmaAtualizacao.setBounds(620, 420, 150, 23);

        tCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCPFKeyTyped(evt);
            }
        });
        getContentPane().add(tCPF);
        tCPF.setBounds(660, 360, 110, 22);

        tItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tItemKeyTyped(evt);
            }
        });
        getContentPane().add(tItem);
        tItem.setBounds(660, 390, 110, 22);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 70, 40);

        tOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Cidade", "Cep", "Bairro", "Rua", "Número" }));
        getContentPane().add(tOpcao);
        tOpcao.setBounds(500, 390, 140, 22);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConfirmaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaAtualizacaoActionPerformed
    String CPF = tCPF.getText();
    String Op = tOpcao.getSelectedItem().toString();
    EnderecoC end = new EnderecoC();
    if (Op == "Estado"){
        String Item = tItem.getText();
        end.AtualizaDentistasEstado(CPF, Item);
    }
    if(Op == "Cidade")
    {
        String Item = tItem.getText();
        end.AtualizaDentistasCidade(CPF, Item);
    }
    if(Op == "Cep"){
        String Item = tItem.getText();
        end.AtualizaDentistasCep(CPF, Item);
    }
    if(Op == "Bairro"){
        String Item = tItem.getText();
        end.AtualizaDentistasBairro(CPF, Item);
    }
    if(Op == "Rua"){
        String Item = tItem.getText();
        end.AtualizaDentistasRua(CPF, Item);
    }
    if(Op == "Número"){
        int Item = Integer.parseInt(tItem.getText());
        end.AtualizaDentistasNumero(CPF, Item);
    }

    dispose();
    new AtualizacaoEnderecoConcluida().setVisible(true);
    }//GEN-LAST:event_ConfirmaAtualizacaoActionPerformed

    private void tCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCPFKeyTyped
       if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        tCPF.setText(tCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       tCPF.setText(tCPF.getText() + ".");
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        tCPF.setText(tCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if (countCPF == 1)
        {
        countCPF = countCPF-2;
        }
        else if (countCPF == 2)
        {
       countCPF = countCPF-2;
        }
        else if (countCPF == 3)
        {
        countCPF = countCPF-2;
        }

    }
    }//GEN-LAST:event_tCPFKeyTyped

    private void tItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tItemKeyTyped
    String tOP = tOpcao.getSelectedItem().toString();

    if (tOP == "Cep"){
        if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tItem.getText().isEmpty()){
            countItem = 0;
        }
            countItem = countItem+1;
        if (countItem == 3)
    {
        tItem.setText(tItem.getText() + ".");
        countItem = countItem+1;
    }
    if (countItem == 7)
    {
       tItem.setText(tItem.getText() + "-");
       countItem = countItem+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countItem > 0){
            countItem = countItem-1;
        }
        else if(countItem == 3){
        countItem = countItem-2;
        }
        else if(countItem == 6){
        countItem = countItem-2;
        }

    }
     }
    }//GEN-LAST:event_tItemKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizacaoEnderecoDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizacaoEnderecoDentista().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontologia Temporaria.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel1.setBounds(
                cx - 135,
                cy - 42,
                150,
                20
        );

        ConfirmaAtualizacao.setBounds(
                cx - 15,
                cy + 18,
                150,
                23
        );

        tCPF.setBounds(
                cx + 25,
                cy - 42,
                110,
                22
        );

        tItem.setBounds(
                cx + 25,
                cy - 12,
                110,
                22
        );

        tOpcao.setBounds(
                cx - 135,
                cy - 12,
                140,
                22
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                70,
                40
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmaAtualizacao;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tCPF;
    private javax.swing.JTextField tItem;
    private javax.swing.JComboBox<String> tOpcao;
    // End of variables declaration//GEN-END:variables
}
