/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Agendamento;
import java.awt.*;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import javax.swing.*;

/**
 *
 * @author guto4
 */
public class Agendamento extends javax.swing.JFrame {

    /**
     * Creates new form Agendamento
     */
    public Agendamento() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        Imagem.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/Imagem/Odontologia Temporaria.png")
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento Dos Dentistas");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);
        jButton1.setText("Consultar Agendamentos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 240, 180, 23);

        jButton2.setText("Deletar Agendamentos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 290, 180, 23);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 460, 75, 40);

        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    new ConsultaAgendamentos().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
    new DeletaAgendamentos().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontologia Temporaria.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jButton1.setBounds(
                cx - 90,
                cy - 36,
                180,
                23
        );

        jButton2.setBounds(
                cx - 90,
                cy + 14,
                180,
                23
        );

        // =====================================
        // VOLTAR
        // =====================================

        jButton3.setBounds(
                15,
                altura - 60,
                75,
                40
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
