/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Agendamento;
import java.awt.*;
import javax.swing.*;

import Controle.AgendamentoC;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guto4
 */
public class ConsultaAgendamentos extends javax.swing.JFrame {
    DefaultTableModel campotabela = new DefaultTableModel();
    ResultSet resposta=null;
    int countCPF = 0;
    AgendamentoC ag = new AgendamentoC();
    public ConsultaAgendamentos() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
        campotabela.addColumn ("ID DO AGENDAMENTO:");
        campotabela.addColumn ("NOME DO PACIENTE:");
        campotabela.addColumn ("NOME DO DENTISTA:");
        campotabela.addColumn ("DATA DO AGENDAMENTO:");
        campotabela.addColumn("Horario");
        jTable1.setModel(campotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        ConsultaPorCPF = new javax.swing.JButton();
        ConsultaGeral = new javax.swing.JButton();
        tCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Agendamento");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 75, 40);

        ConsultaPorCPF.setText("Consulta Por CPF");
        ConsultaPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPorCPFActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaPorCPF);
        ConsultaPorCPF.setBounds(660, 80, 130, 23);

        ConsultaGeral.setText("Consulta Geral");
        ConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaGeralActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaGeral);
        ConsultaGeral.setBounds(540, 80, 110, 23);

        tCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCPFKeyTyped(evt);
            }
        });
        getContentPane().add(tCPF);
        tCPF.setBounds(671, 40, 120, 22);

        jLabel2.setText("Insira o CPF do Médico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 36, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 800, 330);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new Agendamento().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaGeralActionPerformed
        try {
            resposta = ag.ConsultaGeralAgendamento();
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i==1){
                        jTable1.setValueAt(resposta.getInt(i),linha,i-1);
                    }
                    else
                        jTable1.setValueAt(resposta.getString(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();

        }
    }//GEN-LAST:event_ConsultaGeralActionPerformed

    private void ConsultaPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPorCPFActionPerformed
        try {
            String CPF = tCPF.getText();
            resposta = ag.ConsultaPorCPFAgendamentoDentistas(CPF);
            int linha=0;
            //percorre todas as linhas do result set
            while(resposta.next()){
                campotabela.setRowCount(linha+1);
                // laço para percorrer coluna para tabela registro
                for (int i =1; i<=5; i++){
                    if (i==1){
                        jTable1.setValueAt(resposta.getInt(i),linha,i-1);
                    }
                    else
                        jTable1.setValueAt(resposta.getString(i),linha,i-1);
                }
                linha++;
            }
        } catch(Exception erro){
            erro.printStackTrace();

        }
    }//GEN-LAST:event_ConsultaPorCPFActionPerformed

    private void tCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCPFKeyTyped
                     if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        tCPF.setText(tCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       tCPF.setText(tCPF.getText() + ".");
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        tCPF.setText(tCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if (countCPF == 1)
        {
        countCPF = countCPF-2;
        }
        else if (countCPF == 2)
        {
       countCPF = countCPF-2;
        }
        else if (countCPF == 3)
        {
        countCPF = countCPF-2;
        }

    }
    }//GEN-LAST:event_tCPFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAgendamentos().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontologia Temporaria.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        ConsultaPorCPF.setBounds(
                cx + 260,
                cy - 163,
                130,
                23
        );

        ConsultaGeral.setBounds(
                cx + 140,
                cy - 163,
                110,
                23
        );

        tCPF.setBounds(
                cx + 271,
                cy - 203,
                120,
                22
        );

        jLabel2.setBounds(
                cx + 140,
                cy - 207,
                130,
                30
        );

        jScrollPane1.setBounds(
                cx - 400,
                cy - 123,
                800,
                330
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                75,
                40
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaGeral;
    private javax.swing.JButton ConsultaPorCPF;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tCPF;
    // End of variables declaration//GEN-END:variables
}
