/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Agendamento;
import java.awt.*;
import javax.swing.*;
import Controle.AgendamentoC;

/**
 *
 * @author guto4
 */
public class DeletaAgendamentos extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form DeletaAgendamentos
     */
    public DeletaAgendamentos() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        DeletarAgendamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tCPF = new javax.swing.JTextField();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deletar Agendamento");
        setMaximumSize(new java.awt.Dimension(800, 533));
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 80, 40);

        DeletarAgendamento.setText("Deletar Agendamento");
        DeletarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(DeletarAgendamento);
        DeletarAgendamento.setBounds(635, 290, 150, 23);

        jLabel2.setText("No Qual Deseja Deletar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 290, 130, 20);

        jLabel3.setText("Insira O ID Do Agendamento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 260, 160, 20);
        getContentPane().add(tCPF);
        tCPF.setBounds(651, 260, 130, 22);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new Agendamento().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void DeletarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarAgendamentoActionPerformed
     String CPF = tCPF.getText();
     AgendamentoC ag = new AgendamentoC();
     ag.DeletarAgendamento(CPF);

     dispose();
     new AgendamentoDeletado().setVisible(true);
    }//GEN-LAST:event_DeletarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletaAgendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletaAgendamentos().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontologia Temporaria.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        DeletarAgendamento.setBounds(
                cx - 2,
                cy + 4,
                150,
                23
        );

        jLabel2.setBounds(
                cx - 148,
                cy + 4,
                130,
                20
        );

        jLabel3.setBounds(
                cx - 148,
                cy - 26,
                160,
                20
        );

        tCPF.setBounds(
                cx + 14,
                cy - 26,
                130,
                22
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                80,
                40
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletarAgendamento;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tCPF;
    // End of variables declaration//GEN-END:variables
}
