/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Deletar;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.Pacientes.Cadastros.CadastroPaciente;
import Visao.Opcoes.SelecionarOpcoes;
/**
 *
 * @author guto4
 */
public class ConcluiuAExclusao extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form ConcluiuAExclusao
     */
    public ConcluiuAExclusao() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Excluir = new javax.swing.JButton();
        Adicionar = new javax.swing.JButton();
        Retornar = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exclusão Concluida");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel2.setText("Exclusão Concluida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 40, 110, 30);

        Excluir.setText("Excluir Outro Paciente");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir);
        Excluir.setBounds(170, 100, 190, 23);

        Adicionar.setText("Adicionar Um Novo Paciente");
        Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(Adicionar);
        Adicionar.setBounds(170, 140, 190, 23);

        Retornar.setText("Retornar Ao Menu De Opções");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });
        getContentPane().add(Retornar);
        Retornar.setBounds(170, 180, 190, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-130, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
    dispose();
    new DeletarPaciente().setVisible(true);
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
    dispose();
    new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_AdicionarActionPerformed

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcluiuAExclusao().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontoloigia Temporaria2.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel2.setBounds(
                cx - 55,
                cy - 82,
                110,
                30
        );

        Excluir.setBounds(
                cx - 95,
                cy - 22,
                190,
                23
        );

        Adicionar.setBounds(
                cx - 95,
                cy + 18,
                190,
                23
        );

        Retornar.setBounds(
                cx - 95,
                cy + 58,
                190,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Retornar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
