/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Cadastros;
import Controle.*;
import Modelo.*;
import Visao.Opcoes.Pacientes.OpcoesPacientes;
import java.awt.event.KeyEvent;

/**
 *
 * @author guto4
 */
public class CadastroPacienteEndereco extends javax.swing.JFrame {
    int countCPF = 0;
    int countCEP = 0;
    /**
     * Creates new form CadastroPacienteEndereco
     */
    public CadastroPacienteEndereco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tCPF = new javax.swing.JTextField();
        Testado = new javax.swing.JTextField();
        Tcidade = new javax.swing.JTextField();
        tCEP = new javax.swing.JTextField();
        Trua = new javax.swing.JTextField();
        Tnumero = new javax.swing.JTextField();
        Tbairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ConcluirCadastro = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Endereco De Pacientes");
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 470, 80, 30);

        jLabel1.setText("Cpf Do Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 230, 90, 20);

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 260, 80, 20);

        jLabel3.setText("Cidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 290, 90, 20);

        jLabel4.setText("Cep");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 320, 80, 20);

        jLabel5.setText("Rua");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 380, 90, 20);

        jLabel6.setText("Numero");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 410, 90, 20);

        tCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCPFActionPerformed(evt);
            }
        });
        tCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCPFKeyTyped(evt);
            }
        });
        getContentPane().add(tCPF);
        tCPF.setBounds(540, 230, 210, 22);
        getContentPane().add(Testado);
        Testado.setBounds(540, 260, 210, 22);
        getContentPane().add(Tcidade);
        Tcidade.setBounds(540, 290, 210, 22);

        tCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCEPKeyTyped(evt);
            }
        });
        getContentPane().add(tCEP);
        tCEP.setBounds(540, 320, 210, 22);
        getContentPane().add(Trua);
        Trua.setBounds(540, 380, 210, 22);
        getContentPane().add(Tnumero);
        Tnumero.setBounds(540, 410, 210, 22);
        getContentPane().add(Tbairro);
        Tbairro.setBounds(540, 350, 210, 22);

        jLabel7.setText("Bairro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 350, 90, 20);

        ConcluirCadastro.setText("Concluir Cadastro");
        ConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(ConcluirCadastro);
        ConcluirCadastro.setBounds(540, 440, 210, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
     dispose();
     new OpcoesPacientes().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void tCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCPFActionPerformed

    private void ConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirCadastroActionPerformed
    String CPF = tCPF.getText();
    String Estado = Testado.getText();
    String Cidade = Tcidade.getText();
    String Cep = tCEP.getText();
    String Bairro = Tbairro.getText();
    String Rua = Trua.getText();
    int Numero = Integer.parseInt(Tnumero.getText());
    
    EnderecoM end=new EnderecoM(CPF,Estado,Cidade,Cep,Bairro,Rua,Numero);
    EnderecoC endc=new EnderecoC();
    endc.CadastroEnderecoClientes(end);
    
    dispose();
    new CadastroConcluidoEndereco().setVisible(true);
    }//GEN-LAST:event_ConcluirCadastroActionPerformed

    private void tCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCPFKeyTyped
    if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCPF.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        tCPF.setText(tCPF.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       tCPF.setText(tCPF.getText() + ".");
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        tCPF.setText(tCPF.getText() + "-");
        countCPF = countCPF+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if(countCPF == 1){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 2){
        countCPF = countCPF-2;    
        }
        else if(countCPF == 3){
        countCPF = countCPF-2;    
        }
        
    }
    }//GEN-LAST:event_tCPFKeyTyped

    private void tCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCEPKeyTyped
                if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(tCEP.getText().isEmpty()){
          countCEP = 0;
        }
    countCEP = countCEP+1;
        if (countCEP == 3)
    {
        tCEP.setText(tCEP.getText() + ".");
        countCEP = countCEP+1;
    }
    if (countCEP == 7)
    {
       tCEP.setText(tCEP.getText() + "-"); 
       countCEP = countCEP+1;
    }
    }
    
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCEP > 0){
            countCEP = countCEP-1;
        }
        else if(countCEP == 1){
        countCEP = countCEP-2;    
        }
        else if(countCEP == 3){
        countCEP = countCEP-2;    
        }
        
    }
    }//GEN-LAST:event_tCEPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPacienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPacienteEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConcluirCadastro;
    private javax.swing.JLabel Imagem;
    private javax.swing.JTextField Tbairro;
    private javax.swing.JTextField Tcidade;
    private javax.swing.JTextField Testado;
    private javax.swing.JTextField Tnumero;
    private javax.swing.JTextField Trua;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tCEP;
    private javax.swing.JTextField tCPF;
    // End of variables declaration//GEN-END:variables
}
