/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Cadastros;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Pacientes.Agendamento.NovoAgendamento;

public class CadastroConcluidoEndereco extends javax.swing.JFrame {

    /**
     * Creates new form CadastroConcluidoEndereco
     */
    public CadastroConcluidoEndereco() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        RealizarOutroCadastro = new javax.swing.JButton();
        RealizarCadastroPaciente = new javax.swing.JButton();
        RealizarAgendamento = new javax.swing.JButton();
        RetornaMenuOpcoes = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Realizado");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel2.setText("Cadastro Realizado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 30, 110, 20);

        RealizarOutroCadastro.setText("Realizar Outro Cadastro");
        RealizarOutroCadastro.setToolTipText("");
        RealizarOutroCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarOutroCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarOutroCadastro);
        RealizarOutroCadastro.setBounds(150, 80, 210, 23);

        RealizarCadastroPaciente.setText("Realizar Cadastro de Paciente");
        RealizarCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCadastroPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarCadastroPaciente);
        RealizarCadastroPaciente.setBounds(150, 110, 210, 23);

        RealizarAgendamento.setText("Realizar Agendamento do Paciente");
        RealizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarAgendamento);
        RealizarAgendamento.setBounds(150, 140, 214, 23);

        RetornaMenuOpcoes.setText("Retornar Ao Menu de Opções");
        RetornaMenuOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornaMenuOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(RetornaMenuOpcoes);
        RetornaMenuOpcoes.setBounds(150, 170, 210, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-160, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornaMenuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornaMenuOpcoesActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornaMenuOpcoesActionPerformed

    private void RealizarOutroCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarOutroCadastroActionPerformed
    dispose();
    new CadastroPacienteEndereco().setVisible(true);
    }//GEN-LAST:event_RealizarOutroCadastroActionPerformed

    private void RealizarCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCadastroPacienteActionPerformed
    dispose();
    new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_RealizarCadastroPacienteActionPerformed

    private void RealizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarAgendamentoActionPerformed
    dispose();
    new NovoAgendamento().setVisible(true);
    }//GEN-LAST:event_RealizarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluidoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluidoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluidoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluidoEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroConcluidoEndereco().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontoloigia Temporaria2.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel2.setBounds(
                cx - 37,
                cy - 82,
                110,
                20
        );

        RealizarOutroCadastro.setBounds(
                cx - 107,
                cy - 32,
                210,
                23
        );

        RealizarCadastroPaciente.setBounds(
                cx - 107,
                cy - 2,
                210,
                23
        );

        RealizarAgendamento.setBounds(
                cx - 107,
                cy + 28,
                214,
                23
        );

        RetornaMenuOpcoes.setBounds(
                cx - 107,
                cy + 58,
                210,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton RealizarAgendamento;
    private javax.swing.JButton RealizarCadastroPaciente;
    private javax.swing.JButton RealizarOutroCadastro;
    private javax.swing.JButton RetornaMenuOpcoes;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
