/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Cadastros;
import java.awt.*;
import javax.swing.*;
import Modelo.DadosPessoaisM;
import Controle.DadosPessoaisC;
import Visao.Opcoes.Pacientes.OpcoesPacientes;
import java.awt.event.KeyEvent;
/**
 *
 * @author guto4
 */
public class CadastroPaciente extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;
    int countCPF = 0;
    int countContato = 0;
    int countData = 0;
    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente() {
        initComponents();

        getContentPane().setComponentZOrder(
                imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        Tnome = new javax.swing.JLabel();
        Tcpf = new javax.swing.JLabel();
        TDataNasc = new javax.swing.JLabel();
        TContato = new javax.swing.JLabel();
        TSexo = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        jcpf = new javax.swing.JTextField();
        jDataNasc = new javax.swing.JTextField();
        jContato = new javax.swing.JTextField();
        jSexo = new javax.swing.JTextField();
        Cadastro = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Paciente");
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 463, 54, 30);

        Tnome.setText("Nome do Paciente");
        getContentPane().add(Tnome);
        Tnome.setBounds(420, 220, 110, 20);

        Tcpf.setText("CPF Do Paciente");
        getContentPane().add(Tcpf);
        Tcpf.setBounds(420, 260, 100, 20);

        TDataNasc.setText("Data De Nascimento");
        getContentPane().add(TDataNasc);
        TDataNasc.setBounds(420, 290, 110, 20);

        TContato.setText("Contato");
        getContentPane().add(TContato);
        TContato.setBounds(420, 320, 110, 20);

        TSexo.setText("Sexo");
        getContentPane().add(TSexo);
        TSexo.setBounds(420, 350, 120, 20);

        jnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jnome);
        jnome.setBounds(550, 220, 220, 22);

        jcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcpfKeyTyped(evt);
            }
        });
        getContentPane().add(jcpf);
        jcpf.setBounds(550, 258, 220, 22);

        jDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDataNascKeyTyped(evt);
            }
        });
        getContentPane().add(jDataNasc);
        jDataNasc.setBounds(550, 290, 220, 22);

        jContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jContatoKeyTyped(evt);
            }
        });
        getContentPane().add(jContato);
        jContato.setBounds(550, 320, 220, 22);
        getContentPane().add(jSexo);
        jSexo.setBounds(550, 350, 220, 22);

        Cadastro.setText("Concluir Cadastro");
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastro);
        Cadastro.setBounds(550, 390, 220, 23);

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        imagem.setMaximumSize(new java.awt.Dimension(801, 528));
        imagem.setMinimumSize(new java.awt.Dimension(801, 528));
        imagem.setPreferredSize(new java.awt.Dimension(801, 528));
        getContentPane().add(imagem);
        imagem.setBounds(0, 0, 801, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomeActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesPacientes().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed
        String nome = jnome.getText();
        String CPF = jcpf.getText();
        String Data_nasc=jDataNasc.getText();
        String Contato = jContato.getText();
        String texto=jSexo.getText();
        char sexo = texto.charAt(0);

    DadosPessoaisM dp = new DadosPessoaisM(nome,CPF,Data_nasc,Contato,sexo);
    DadosPessoaisC dc = new DadosPessoaisC();
    dc.CadastroGeralClientes(dp);
    new CadastroConcluidoPaciente().setVisible(true);
    dispose();

    }//GEN-LAST:event_CadastroActionPerformed

    private void jcpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcpfKeyTyped
     if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(jcpf.getText().isEmpty()){
          countCPF = 0;
        }
        countCPF = countCPF+1;
        if (countCPF == 4)
    {
        jcpf.setText(jcpf.getText() + ".");
        countCPF = countCPF+1;
    }
    if (countCPF == 8)
    {
       jcpf.setText(jcpf.getText() + ".");
       countCPF = countCPF+1;
    }
    if (countCPF == 12){
        jcpf.setText(jcpf.getText() + "-");
        countCPF = countCPF+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countCPF > 0){
            countCPF = countCPF-1;
        }
        else if(countCPF == 1){
        countCPF = countCPF-2;
        }
        else if(countCPF == 2){
        countCPF = countCPF-2;
        }
        else if(countCPF == 3){
        countCPF = countCPF-2;
        }

    }
    }//GEN-LAST:event_jcpfKeyTyped

    private void jDataNascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDataNascKeyTyped
     if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(jDataNasc.getText().isEmpty()){
            countData = 0;
        }
            countData = countData+1;
        if (countData == 3)
    {
        jDataNasc.setText(jDataNasc.getText() + "/");
        countData = countData+1;
    }
    if (countData == 6)
    {
       jDataNasc.setText(jDataNasc.getText() + "/");
       countData = countData+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countData > 0){
            countData = countData-1;
        }
        else if(countData == 1){
        countData = countData-2;
        }
        else if(countData == 3){
        countData = countData-2;
        }

    }
    }//GEN-LAST:event_jDataNascKeyTyped

    private void jContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jContatoKeyTyped
     if(evt.getKeyChar() == '0' |evt.getKeyChar() == '1' |evt.getKeyChar() == '2'|evt.getKeyChar() == '3'
            |evt.getKeyChar() == '4'|evt.getKeyChar() == '5'|evt.getKeyChar() == '6'|evt.getKeyChar() == '7'|evt.getKeyChar() == '8'|evt.getKeyChar() == '9'){
        if(jContato.getText().isEmpty()){
            countContato = 0;
        }
    countContato = countContato+1;
        if (countContato == 1)
    {
        jContato.setText(jContato.getText() + "(");
        countContato = countContato+1;
    }
    if (countContato == 4)
    {
       jContato.setText(jContato.getText() + ")");
       countContato = countContato+1;
    }
    if (countContato == 10){
        jContato.setText(jContato.getText() + "-");
        countContato = countContato+1;
    }
    }

    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
        if (countContato > 0){
            countContato = countContato-1;
        }
        else if(countContato == 1){
        countContato = countContato-2;
        }
        else if(countContato == 4){
        countContato = countContato-2;
        }
        else if(countContato == 10){
        countContato = countContato-2;
        }

    }
    }//GEN-LAST:event_jContatoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontologia Temporaria.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                imagem.getWidth(),
                imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        Tnome.setBounds(
                cx - 175,
                cy - 96,
                110,
                20
        );

        Tcpf.setBounds(
                cx - 175,
                cy - 56,
                100,
                20
        );

        TDataNasc.setBounds(
                cx - 175,
                cy - 26,
                110,
                20
        );

        TContato.setBounds(
                cx - 175,
                cy + 4,
                110,
                20
        );

        TSexo.setBounds(
                cx - 175,
                cy + 34,
                120,
                20
        );

        jnome.setBounds(
                cx - 45,
                cy - 96,
                220,
                22
        );

        jcpf.setBounds(
                cx - 45,
                cy - 58,
                220,
                22
        );

        jDataNasc.setBounds(
                cx - 45,
                cy - 26,
                220,
                22
        );

        jContato.setBounds(
                cx - 45,
                cy + 4,
                220,
                22
        );

        jSexo.setBounds(
                cx - 45,
                cy + 34,
                220,
                22
        );

        Cadastro.setBounds(
                cx - 45,
                cy + 74,
                220,
                23
        );

        // =====================================
        // VOLTAR
        // =====================================

        Voltar.setBounds(
                15,
                altura - 60,
                54,
                30
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastro;
    private javax.swing.JLabel TContato;
    private javax.swing.JLabel TDataNasc;
    private javax.swing.JLabel TSexo;
    private javax.swing.JLabel Tcpf;
    private javax.swing.JLabel Tnome;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel imagem;
    private javax.swing.JTextField jContato;
    private javax.swing.JTextField jDataNasc;
    private javax.swing.JTextField jSexo;
    private javax.swing.JTextField jcpf;
    private javax.swing.JTextField jnome;
    // End of variables declaration//GEN-END:variables
}
