/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes;

import Visao.Opcoes.Pacientes.OpcoesPacientes;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import Visao.TelaInicial.TelaInicial;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author guto4
 */
public class SelecionarOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarOpcoes
     */
    public SelecionarOpcoes() {

        initComponents();

        ConfigurarImagem();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        addComponentListener(new java.awt.event.ComponentAdapter() {

            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPacientes = new javax.swing.JButton();
        BtnDentista = new javax.swing.JButton();
        BtnTelaInicial = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Opções");
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);
        // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 530);

        BtnPacientes.setText("Opções para Pacientes");
        BtnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPacientes);
        BtnPacientes.setBounds(300, 240, 210, 23);

        BtnDentista.setText("Opções para Dentistas");
        BtnDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDentista);
        BtnDentista.setBounds(300, 290, 210, 23);

        BtnTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        BtnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTelaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTelaInicial);
        BtnTelaInicial.setBounds(0, 460, 60, 30);


        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void ConfigurarImagem() {

        java.net.URL url = getClass()
                .getResource("/Imagem/Odontologia Temporaria.png");

        if (url == null) {
            System.out.println("Imagem não encontrada!");
            return;
        }


        Image imagem = new ImageIcon(url).getImage();


        Imagem = new JLabel() {

            @Override
            protected void paintComponent(java.awt.Graphics g) {

                super.paintComponent(g);

                g.drawImage(
                        imagem,
                        0,
                        0,
                        getWidth(),
                        getHeight(),
                        this
                );
            }
        };


        getContentPane().add(Imagem);
        getContentPane().setComponentZOrder(BtnPacientes, 0);
        getContentPane().setComponentZOrder(BtnDentista, 0);
        getContentPane().setComponentZOrder(BtnTelaInicial, 0);

    }
    private void BtnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTelaInicialActionPerformed
        abrirTela(new TelaInicial());
    }//GEN-LAST:event_BtnTelaInicialActionPerformed

    private void BtnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPacientesActionPerformed
     abrirTela(new OpcoesPacientes());
    }//GEN-LAST:event_BtnPacientesActionPerformed

    private void BtnDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDentistaActionPerformed
    abrirTela(new OpcoesDentistas());
    }//GEN-LAST:event_BtnDentistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
                new SelecionarOpcoes().setVisible(true)
        );
    }

    private void abrirTela(javax.swing.JFrame tela) {
        dispose();
        tela.setLocationRelativeTo(null); // Centraliza a janela
        tela.setVisible(true);
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();


        // imagem ocupa toda a tela
        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );


        int larguraBotao = 220;
        int alturaBotao = 30;


        int x = (largura - larguraBotao) / 2;

        int y = (altura / 2) - 50;


        BtnPacientes.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );


        BtnDentista.setBounds(
                x,
                y + 50,
                larguraBotao,
                alturaBotao
        );


        BtnTelaInicial.setBounds(
                15,
                altura - 60,
                45,
                45
        );


        Imagem.repaint();
        BtnPacientes.repaint();
        BtnDentista.repaint();
        BtnTelaInicial.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton BtnPacientes;
    private javax.swing.JButton BtnDentista;
    private javax.swing.JButton BtnTelaInicial;
    // End of variables declaration//GEN-END:variables
}
