/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes;

import Visao.Opcoes.Pacientes.OpcoesPacientes;
import Visao.Opcoes.Dentistas.OpcoesDentistas;
import Visao.TelaInicial.TelaInicial;

/**
 *
 * @author guto4
 */
public class SelecionarOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarOpcoes
     */
    public SelecionarOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selecionar_Paciente = new javax.swing.JButton();
        Selecionar_dentistas = new javax.swing.JButton();
        VoltarTelaInicial = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Opções");
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        Selecionar_Paciente.setText("Opções para Pacientes");
        Selecionar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(Selecionar_Paciente);
        Selecionar_Paciente.setBounds(300, 240, 210, 23);

        Selecionar_dentistas.setText("Opções para Dentistas");
        Selecionar_dentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_dentistasActionPerformed(evt);
            }
        });
        getContentPane().add(Selecionar_dentistas);
        Selecionar_dentistas.setBounds(300, 290, 210, 23);

        VoltarTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        VoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarTelaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarTelaInicial);
        VoltarTelaInicial.setBounds(0, 460, 60, 30);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarTelaInicialActionPerformed
        dispose();
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_VoltarTelaInicialActionPerformed

    private void Selecionar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_PacienteActionPerformed
     dispose();
     new OpcoesPacientes().setVisible(true);
    }//GEN-LAST:event_Selecionar_PacienteActionPerformed

    private void Selecionar_dentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_dentistasActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_Selecionar_dentistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Selecionar_Paciente;
    private javax.swing.JButton Selecionar_dentistas;
    private javax.swing.JButton VoltarTelaInicial;
    // End of variables declaration//GEN-END:variables
}
