/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes;

import Visao.Opcoes.Pacientes.Cadastros.CadastroPaciente;
import Visao.Opcoes.Pacientes.Cadastros.CadastroPacienteEndereco;
import Visao.Opcoes.Pacientes.Consulta.ConsultaPacientes;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Pacientes.Deletar.DeletarPaciente;
import Visao.Opcoes.Pacientes.Agendamento.Agendamento;
import Visao.Opcoes.Pacientes.Atualizacao.AtualizaDadosPessoais;
import Visao.Opcoes.Pacientes.Atualizacao.AtualizaEndereco;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author guto4
 */
public class OpcoesPacientes extends javax.swing.JFrame {

    /**
     * Creates new form OpcoesPacientes
     */
    public OpcoesPacientes() {
        initComponents();
        ConfigurarImagem();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        addComponentListener(new java.awt.event.ComponentAdapter() {

            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastro_Paciente = new javax.swing.JButton();
        ConsultaPaciente = new javax.swing.JButton();
        AgendarPaciente = new javax.swing.JButton();
        DeletarPaciente = new javax.swing.JButton();
        VoltarAsOpcoes = new javax.swing.JButton();
        CadastroEndereco = new javax.swing.JButton();
        AtualizarDadosPaciente = new javax.swing.JButton();
        AtualizarEndereco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opções Pacientes");
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 530);
        Cadastro_Paciente.setText("Cadastrar Paciente");
        Cadastro_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastro_Paciente);
        Cadastro_Paciente.setBounds(310, 180, 220, 23);

        ConsultaPaciente.setText("Consulta Pacientes Cadastrados");
        ConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaPaciente);
        ConsultaPaciente.setBounds(310, 300, 220, 23);

        AgendarPaciente.setText("Agendamentos de Pacientes");
        AgendarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(AgendarPaciente);
        AgendarPaciente.setBounds(310, 330, 220, 23);

        DeletarPaciente.setText("Deletar Paciente");
        DeletarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(DeletarPaciente);
        DeletarPaciente.setBounds(310, 360, 220, 23);

        VoltarAsOpcoes.setBackground(new java.awt.Color(242, 242, 242));
        VoltarAsOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        VoltarAsOpcoes.setBorder(null);
        VoltarAsOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAsOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarAsOpcoes);
        VoltarAsOpcoes.setBounds(0, 460, 70, 30);

        CadastroEndereco.setText("Cadastro De Endereço do Paciente");
        CadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroEndereco);
        CadastroEndereco.setBounds(310, 240, 220, 23);

        AtualizarDadosPaciente.setText("Atualizar Dados De Pacientes");
        AtualizarDadosPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarDadosPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizarDadosPaciente);
        AtualizarDadosPaciente.setBounds(310, 210, 220, 23);

        AtualizarEndereco.setText("Atualizar Endereco De Pacientes");
        AtualizarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizarEndereco);
        AtualizarEndereco.setBounds(310, 270, 200, 23);


        pack();
        setSize(801, 528);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigurarImagem() {

        java.net.URL url = getClass()
                .getResource("/Imagem/Odontologia Temporaria.png");

        if (url == null) {
            System.out.println("Imagem não encontrada!");
            return;
        }


        Image imagem = new ImageIcon(url).getImage();


        jLabel1 = new JLabel() {

            @Override
            protected void paintComponent(java.awt.Graphics g) {

                super.paintComponent(g);

                g.drawImage(
                        imagem,
                        0,
                        0,
                        getWidth(),
                        getHeight(),
                        this
                );
            }
        };


        getContentPane().add(jLabel1);
        getContentPane().setComponentZOrder(AgendarPaciente, 0);
        getContentPane().setComponentZOrder(Cadastro_Paciente, 0);
        getContentPane().setComponentZOrder(CadastroEndereco, 0);
        getContentPane().setComponentZOrder(ConsultaPaciente, 0);
        getContentPane().setComponentZOrder(DeletarPaciente, 0);
        getContentPane().setComponentZOrder(VoltarAsOpcoes, 0);
        getContentPane().setComponentZOrder(AtualizarDadosPaciente, 0);
        getContentPane().setComponentZOrder(AtualizarEndereco, 0);
    }

    private void ConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPacienteActionPerformed
    dispose();
    new ConsultaPacientes().setVisible(true);
    }//GEN-LAST:event_ConsultaPacienteActionPerformed

    private void VoltarAsOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAsOpcoesActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_VoltarAsOpcoesActionPerformed

    private void Cadastro_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_PacienteActionPerformed
    dispose();
    new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_Cadastro_PacienteActionPerformed

    private void CadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroEnderecoActionPerformed
    dispose();
    new CadastroPacienteEndereco().setVisible(true);
    }//GEN-LAST:event_CadastroEnderecoActionPerformed

    private void DeletarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarPacienteActionPerformed
    dispose();
    new DeletarPaciente().setVisible(true);
    }//GEN-LAST:event_DeletarPacienteActionPerformed

    private void AgendarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarPacienteActionPerformed
    dispose();
    new Agendamento().setVisible(true);
    }//GEN-LAST:event_AgendarPacienteActionPerformed

    private void AtualizarDadosPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarDadosPacienteActionPerformed
    dispose();
    new AtualizaDadosPessoais().setVisible(true);
    }//GEN-LAST:event_AtualizarDadosPacienteActionPerformed

    private void AtualizarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarEnderecoActionPerformed
    dispose();
    new AtualizaEndereco().setVisible(true);
    }//GEN-LAST:event_AtualizarEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcoesPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcoesPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcoesPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcoesPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcoesPacientes().setVisible(true);
            }
        });
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();


        // imagem ocupa toda a tela
        jLabel1.setBounds(
                0,
                0,
                largura,
                altura
        );


        int larguraBotao = 220;
        int alturaBotao = 30;


        int x = (largura - larguraBotao) / 2;

        int y = (altura / 2) - 50;

        AgendarPaciente.setBounds(
                x,
                y+160,
                larguraBotao,
                alturaBotao
        );

        Cadastro_Paciente.setBounds(
                x,
                y,
                larguraBotao,
                alturaBotao
        );

        CadastroEndereco.setBounds(
                x,
                y+40,
                larguraBotao,
                alturaBotao
        );

        ConsultaPaciente.setBounds(
                x,
                y+200,
                larguraBotao,
                alturaBotao
        );

        DeletarPaciente.setBounds(
                x,
                y+240,
                larguraBotao,
                alturaBotao
        );

        VoltarAsOpcoes.setBounds(
                15,
                altura - 60,
                45,
                45
        );

        AtualizarDadosPaciente.setBounds(
                x,
                y+80,
                larguraBotao,
                alturaBotao
        );

        AtualizarEndereco.setBounds(
                x,
                y+120,
                larguraBotao,
                alturaBotao
        );


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarPaciente;
    private javax.swing.JButton AtualizarDadosPaciente;
    private javax.swing.JButton AtualizarEndereco;
    private javax.swing.JButton CadastroEndereco;
    private javax.swing.JButton Cadastro_Paciente;
    private javax.swing.JButton ConsultaPaciente;
    private javax.swing.JButton DeletarPaciente;
    private javax.swing.JButton VoltarAsOpcoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
