/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Deletar;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Dentistas.Cadastro.CadastroDentista;
/**
 *
 * @author guto4
 */
public class ConcluiuAExclusao extends javax.swing.JFrame {

    /**
     * Creates new form ConcluiuAExclusao
     */
    public ConcluiuAExclusao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExcluirDentista = new javax.swing.JButton();
        CadastroDentista = new javax.swing.JButton();
        RetornaAoMenuDeOpcoes = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Exclusão Realizada");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 50, 100, 16);

        ExcluirDentista.setText("Excluir Outro Dentista");
        ExcluirDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(ExcluirDentista);
        ExcluirDentista.setBounds(160, 100, 200, 23);

        CadastroDentista.setText("Cadastrar Um Novo Dentista");
        CadastroDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroDentista);
        CadastroDentista.setBounds(160, 140, 200, 23);

        RetornaAoMenuDeOpcoes.setText("Retornar Ao Menu De Opções");
        RetornaAoMenuDeOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornaAoMenuDeOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(RetornaAoMenuDeOpcoes);
        RetornaAoMenuDeOpcoes.setBounds(160, 180, 200, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-130, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornaAoMenuDeOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornaAoMenuDeOpcoesActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornaAoMenuDeOpcoesActionPerformed

    private void CadastroDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDentistaActionPerformed
    dispose();
    new CadastroDentista().setVisible(true);
    }//GEN-LAST:event_CadastroDentistaActionPerformed

    private void ExcluirDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirDentistaActionPerformed
    dispose();
    new DeletarDentista().setVisible(true);
    }//GEN-LAST:event_ExcluirDentistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcluiuAExclusao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroDentista;
    private javax.swing.JButton ExcluirDentista;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton RetornaAoMenuDeOpcoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
