/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Deletar;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Dentistas.Cadastro.CadastroDentista;
/**
 *
 * @author guto4
 */
public class ConcluiuAExclusao extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form ConcluiuAExclusao
     */
    public ConcluiuAExclusao() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ExcluirDentista = new javax.swing.JButton();
        CadastroDentista = new javax.swing.JButton();
        RetornaAoMenuDeOpcoes = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel1.setText("Exclusão Realizada");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 50, 100, 16);

        ExcluirDentista.setText("Excluir Outro Dentista");
        ExcluirDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(ExcluirDentista);
        ExcluirDentista.setBounds(160, 100, 200, 23);

        CadastroDentista.setText("Cadastrar Um Novo Dentista");
        CadastroDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDentistaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroDentista);
        CadastroDentista.setBounds(160, 140, 200, 23);

        RetornaAoMenuDeOpcoes.setText("Retornar Ao Menu De Opções");
        RetornaAoMenuDeOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornaAoMenuDeOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(RetornaAoMenuDeOpcoes);
        RetornaAoMenuDeOpcoes.setBounds(160, 180, 200, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-130, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornaAoMenuDeOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornaAoMenuDeOpcoesActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornaAoMenuDeOpcoesActionPerformed

    private void CadastroDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDentistaActionPerformed
    dispose();
    new CadastroDentista().setVisible(true);
    }//GEN-LAST:event_CadastroDentistaActionPerformed

    private void ExcluirDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirDentistaActionPerformed
    dispose();
    new DeletarDentista().setVisible(true);
    }//GEN-LAST:event_ExcluirDentistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcluiuAExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcluiuAExclusao().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontoloigia Temporaria2.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel1.setBounds(
                cx - 50,
                cy - 76,
                100,
                16
        );

        ExcluirDentista.setBounds(
                cx - 100,
                cy - 26,
                200,
                23
        );

        CadastroDentista.setBounds(
                cx - 100,
                cy + 14,
                200,
                23
        );

        RetornaAoMenuDeOpcoes.setBounds(
                cx - 100,
                cy + 54,
                200,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroDentista;
    private javax.swing.JButton ExcluirDentista;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton RetornaAoMenuDeOpcoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
