/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Atualizacao;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Pacientes.Consulta.ConsultaPacientes;
import Visao.Opcoes.Pacientes.Cadastros.CadastroPaciente;

/**
 *
 * @author guto4
 */
public class AtualizaDadosConcluido extends javax.swing.JFrame {

    /**
     * Creates new form AtualizaDadosConcluido
     */
    public AtualizaDadosConcluido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        RealizarUmaNovaAtualizacao = new javax.swing.JButton();
        AdicionarUmNovoPaciente = new javax.swing.JButton();
        ConsultaDePacientes = new javax.swing.JButton();
        RetornarAoMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização De Dados Pessoais Concluida");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel2.setText("Atualização De Dados Do Paciente Concluida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 40, 250, 20);

        RealizarUmaNovaAtualizacao.setText("Realizar Uma Nova Atualização");
        RealizarUmaNovaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarUmaNovaAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarUmaNovaAtualizacao);
        RealizarUmaNovaAtualizacao.setBounds(150, 100, 220, 23);

        AdicionarUmNovoPaciente.setText("Adicionar Um Novo Paciente");
        AdicionarUmNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarUmNovoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarUmNovoPaciente);
        AdicionarUmNovoPaciente.setBounds(150, 130, 220, 23);

        ConsultaDePacientes.setText("Consultar Pacientes Já Cadastrados");
        ConsultaDePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaDePacientesActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaDePacientes);
        ConsultaDePacientes.setBounds(150, 160, 220, 23);

        RetornarAoMenu.setText("Retornar Ao Menu De Opções");
        RetornarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RetornarAoMenu);
        RetornarAoMenu.setBounds(150, 190, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarAoMenuActionPerformed

    private void ConsultaDePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDePacientesActionPerformed
    dispose();
    new ConsultaPacientes().setVisible(true);
    }//GEN-LAST:event_ConsultaDePacientesActionPerformed

    private void AdicionarUmNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarUmNovoPacienteActionPerformed
    dispose();
    new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_AdicionarUmNovoPacienteActionPerformed

    private void RealizarUmaNovaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarUmaNovaAtualizacaoActionPerformed
    dispose();
    new AtualizaDadosPessoais().setVisible(true);
    }//GEN-LAST:event_RealizarUmaNovaAtualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaDadosConcluido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarUmNovoPaciente;
    private javax.swing.JButton ConsultaDePacientes;
    private javax.swing.JButton RealizarUmaNovaAtualizacao;
    private javax.swing.JButton RetornarAoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
