/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Atualizacao;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.SelecionarOpcoes;
import Visao.Opcoes.Pacientes.Consulta.ConsultaPacientes;
import Visao.Opcoes.Pacientes.Cadastros.CadastroPaciente;

/**
 *
 * @author guto4
 */
public class AtualizaDadosConcluido extends javax.swing.JFrame {

    /**
     * Creates new form AtualizaDadosConcluido
     */
    public AtualizaDadosConcluido() {
        initComponents();

        getContentPane().setComponentZOrder(
                jLabel1,
                getContentPane().getComponentCount() - 1
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        RealizarUmaNovaAtualizacao = new javax.swing.JButton();
        AdicionarUmNovoPaciente = new javax.swing.JButton();
        ConsultaDePacientes = new javax.swing.JButton();
        RetornarAoMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização De Dados Pessoais Concluida");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel2.setText("Atualização De Dados Do Paciente Concluida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 40, 250, 20);

        RealizarUmaNovaAtualizacao.setText("Realizar Uma Nova Atualização");
        RealizarUmaNovaAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarUmaNovaAtualizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarUmaNovaAtualizacao);
        RealizarUmaNovaAtualizacao.setBounds(150, 100, 220, 23);

        AdicionarUmNovoPaciente.setText("Adicionar Um Novo Paciente");
        AdicionarUmNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarUmNovoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarUmNovoPaciente);
        AdicionarUmNovoPaciente.setBounds(150, 130, 220, 23);

        ConsultaDePacientes.setText("Consultar Pacientes Já Cadastrados");
        ConsultaDePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaDePacientesActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaDePacientes);
        ConsultaDePacientes.setBounds(150, 160, 220, 23);

        RetornarAoMenu.setText("Retornar Ao Menu De Opções");
        RetornarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(RetornarAoMenu);
        RetornarAoMenu.setBounds(150, 190, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetornarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_RetornarAoMenuActionPerformed

    private void ConsultaDePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDePacientesActionPerformed
    dispose();
    new ConsultaPacientes().setVisible(true);
    }//GEN-LAST:event_ConsultaDePacientesActionPerformed

    private void AdicionarUmNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarUmNovoPacienteActionPerformed
    dispose();
    new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_AdicionarUmNovoPacienteActionPerformed

    private void RealizarUmaNovaAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarUmaNovaAtualizacaoActionPerformed
    dispose();
    new AtualizaDadosPessoais().setVisible(true);
    }//GEN-LAST:event_RealizarUmaNovaAtualizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaDadosConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaDadosConcluido().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/Imagem/Odontoloigia Temporaria2.png"
                )
        );

        Image imagem = iconeOriginal.getImage();

        Image imagemRedimensionada = imagem.getScaledInstance(
                jLabel1.getWidth(),
                jLabel1.getHeight(),
                Image.SCALE_SMOOTH
        );

        jLabel1.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        jLabel1.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel2.setBounds(
                cx - 125,
                cy - 86,
                250,
                20
        );

        RealizarUmaNovaAtualizacao.setBounds(
                cx - 125,
                cy - 26,
                220,
                23
        );

        AdicionarUmNovoPaciente.setBounds(
                cx - 125,
                cy + 4,
                220,
                23
        );

        ConsultaDePacientes.setBounds(
                cx - 125,
                cy + 34,
                220,
                23
        );

        RetornarAoMenu.setBounds(
                cx - 125,
                cy + 64,
                220,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarUmNovoPaciente;
    private javax.swing.JButton ConsultaDePacientes;
    private javax.swing.JButton RealizarUmaNovaAtualizacao;
    private javax.swing.JButton RetornarAoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
