/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Pacientes.Atualizacao;
import java.awt.*;
import javax.swing.*;
import Visao.Opcoes.Pacientes.Cadastros.CadastroPacienteEndereco;
import Visao.Opcoes.Pacientes.Consulta.ConsultaPacientesEndereco;
import Visao.Opcoes.SelecionarOpcoes;
/**
 *
 * @author guto4
 */
public class AtualizaEnderecoConcluido extends javax.swing.JFrame {
    private Image imagemOriginalCache = null;

    /**
     * Creates new form AtualizaEnderecoConcluido
     */
    public AtualizaEnderecoConcluido() {
        initComponents();

        getContentPane().setComponentZOrder(
                Imagem,
                getContentPane().getComponentCount() - 1
        );

        // Reaplica o estado (maximizada ou nao) que o usuario estava usando
        if (Utilitarios.EstadoJanela.maximizada) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        // Guarda o estado atual sempre que o usuario maximizar/restaurar a janela
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                Utilitarios.EstadoJanela.maximizada =
                        (getExtendedState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH;
            }
        });

        // Ajusta a tela ao tamanho da janela
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarTela();
            }
        });

        SwingUtilities.invokeLater(() -> {
            ajustarTela();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AtualizaOutroEndereco = new javax.swing.JButton();
        CadastroNovoEndereco = new javax.swing.JButton();
        VoltarAoMenu = new javax.swing.JButton();
        ConsultaNovoEndereco = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualização De Endereço Do Paciente Concluida");
        setMaximumSize(new java.awt.Dimension(521, 275));
        setMinimumSize(new java.awt.Dimension(521, 275));
        getContentPane().setLayout(null);

        jLabel2.setText("Atualização Do Endereço Do Paciente Concluida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 50, 270, 30);

        AtualizaOutroEndereco.setText("Atualizar Outro Endereço");
        AtualizaOutroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizaOutroEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizaOutroEndereco);
        AtualizaOutroEndereco.setBounds(150, 100, 210, 23);

        CadastroNovoEndereco.setText("Cadastrar Um Novo Endereço");
        CadastroNovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroNovoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroNovoEndereco);
        CadastroNovoEndereco.setBounds(150, 130, 210, 23);

        VoltarAoMenu.setText("Retornar Ao Menu De Opções");
        VoltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarAoMenu);
        VoltarAoMenu.setBounds(150, 190, 210, 23);

        ConsultaNovoEndereco.setText("Consultar Endereços Cadastrados");
        ConsultaNovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaNovoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaNovoEndereco);
        ConsultaNovoEndereco.setBounds(150, 160, 210, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontoloigia Temporaria2.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(-150, -170, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizaOutroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizaOutroEnderecoActionPerformed
    dispose();
    new AtualizaEndereco().setVisible(true);
    }//GEN-LAST:event_AtualizaOutroEnderecoActionPerformed

    private void CadastroNovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroNovoEnderecoActionPerformed
    dispose();
    new CadastroPacienteEndereco().setVisible(true);
    }//GEN-LAST:event_CadastroNovoEnderecoActionPerformed

    private void ConsultaNovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaNovoEnderecoActionPerformed
    dispose();
    new ConsultaPacientesEndereco().setVisible(true);
    }//GEN-LAST:event_ConsultaNovoEnderecoActionPerformed

    private void VoltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenuActionPerformed
    dispose();
    new SelecionarOpcoes().setVisible(true);
    }//GEN-LAST:event_VoltarAoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaEnderecoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaEnderecoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaEnderecoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaEnderecoConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaEnderecoConcluido().setVisible(true);
            }
        });
    }

        private void atualizarImagem() {

        if (imagemOriginalCache == null) {
            imagemOriginalCache = new ImageIcon(
                    getClass().getResource("/Imagem/Odontoloigia Temporaria2.png")
            ).getImage();
        }

        Image imagemRedimensionada = imagemOriginalCache.getScaledInstance(
                Imagem.getWidth(),
                Imagem.getHeight(),
                Image.SCALE_SMOOTH
        );

        Imagem.setIcon(
                new ImageIcon(imagemRedimensionada)
        );
    }

    private void ajustarTela() {

        int largura = getContentPane().getWidth();
        int altura = getContentPane().getHeight();

        // =====================================
        // IMAGEM DE FUNDO
        // =====================================

        Imagem.setBounds(
                0,
                0,
                largura,
                altura
        );

        atualizarImagem();

        // =====================================
        // COMPONENTES (mantêm a posição relativa do layout original)
        // =====================================

        int cx = largura / 2;
        int cy = altura / 2;

        jLabel2.setBounds(
                cx - 135,
                cy - 82,
                270,
                30
        );

        AtualizaOutroEndereco.setBounds(
                cx - 115,
                cy - 32,
                210,
                23
        );

        CadastroNovoEndereco.setBounds(
                cx - 115,
                cy - 2,
                210,
                23
        );

        VoltarAoMenu.setBounds(
                cx - 115,
                cy + 58,
                210,
                23
        );

        ConsultaNovoEndereco.setBounds(
                cx - 115,
                cy + 28,
                210,
                23
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizaOutroEndereco;
    private javax.swing.JButton CadastroNovoEndereco;
    private javax.swing.JButton ConsultaNovoEndereco;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton VoltarAoMenu;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
