/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.Opcoes.Dentistas.Consulta;
import Visao.Opcoes.Dentistas.OpcoesDentistas;

/**
 *
 * @author guto4
 */
public class ConsultaDentistas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaDentistas
     */
    public ConsultaDentistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaDentistaCadastrado = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        ConsultaDentistaEndereco = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Dentistas");
        setMaximumSize(new java.awt.Dimension(801, 528));
        setMinimumSize(new java.awt.Dimension(801, 528));
        getContentPane().setLayout(null);

        ConsultaDentistaCadastrado.setText("Consulta Dentistas Cadastrados");
        ConsultaDentistaCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaDentistaCadastradoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaDentistaCadastrado);
        ConsultaDentistaCadastrado.setBounds(290, 230, 220, 23);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/216437_back_arrow_icon.png"))); // NOI18N
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 460, 70, 30);

        ConsultaDentistaEndereco.setText("Consulta Endereco De Dentistas");
        ConsultaDentistaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaDentistaEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultaDentistaEndereco);
        ConsultaDentistaEndereco.setBounds(290, 270, 220, 23);

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Odontologia Temporaria.png"))); // NOI18N
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
    dispose();
    new OpcoesDentistas().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConsultaDentistaCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDentistaCadastradoActionPerformed
    dispose();
    new ConsultaDentistaCadastrado().setVisible(true);
    }//GEN-LAST:event_ConsultaDentistaCadastradoActionPerformed

    private void ConsultaDentistaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDentistaEnderecoActionPerformed
    dispose();
    new ConsultaDentistaEndereco().setVisible(true);
    }//GEN-LAST:event_ConsultaDentistaEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDentistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaDentistaCadastrado;
    private javax.swing.JButton ConsultaDentistaEndereco;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Voltar;
    // End of variables declaration//GEN-END:variables
}
